Update react-async-script
lemieux/react-messenger-plugin pull request #9
Opened 2017-08-20 09:31 UTC by nonken

The referenced version of `react-async-script` was still using React.PropTypes. Updated to latest.

2017-08-21 14:03 UTC, lemieux requested changes
Hey! thanks for the contribution :) 

Just need to bring back the ignore rules and remove the files that were committed and I'll publish a new version.

2017-08-21 14:03 UTC, lemieux commented on .gitignore
> -lib
This should stay ignored and the files in the folder that were comitted should not be here.

2017-11-02 12:53 UTC, jmoulin-vp commented
Hi, can this pull request be merged ? we can't update to React 16 with this old version of react-async-script

2017-11-02 13:22 UTC, lemieux commented
Sure, I'll close this PR and redo the changes in a branch.

2017-11-02 13:33 UTC, lemieux commented
Fixed on v2.0.0 and available on npm.

2017-11-02 13:33 UTC, closed without merging

2017-11-02 16:30 UTC, jmoulin-vp commented
thanks ! it works perfectly

2017-11-02 19:33 UTC, nonken commented
I completely missed this! Thanks for updating and sorry for being very slow responding!